name: CI/CD Debug

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches: 
      - int-**


jobs: 

    print_event:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Print PR
          run: |
            echo  "PR #"
            echo  ${{ github.event.pull_request.number }}
           