name: CI/CD Automatic Process

on:
  push:
    branches: [ "feature/*"  ]
  # pull_request:
  #   branches: [ "int-*"  ]


jobs: 
  
    create_pull_request:

      runs-on: ubuntu-latest
      environment:
        name: development
  
      steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Create Pull Request
          id: create_pr
          env:
            GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
          run: |
            PR_NUMBER=$(gh pr list --state "open" --head "${{ github.ref_name }}" --base "${{ vars.DESTINATION_BRANCH }}" --json number --jq 'length > 0')
            #--head ${{ github.ref_name }} --base ${{ vars.DESTINATION_BRANCH }} .[0].number --jq 'length > 0'
            if [[ -n "$PR_NUMBER" ]]; then
              echo "the pr number is: $PR_NUMBER"
            else
              gh pr create --head ${{ github.ref_name }} --base ${{ vars.DESTINATION_BRANCH }} --title "Pull request from ${{ github.ref_name }} to ${{ vars.DESTINATION_BRANCH }}" --body ""
            fi


    merge_pull_request:

      runs-on: ubuntu-latest
      needs: create_pull_request
      environment:
        name: development
  

      steps:
        
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Merge Pull Request
          id: create_pr
          env:
            GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
          run: |
            PR_NUMBER=$(gh pr list --state "open" --json number --jq '.[0].number')
            gh pr merge $PR_NUMBER --merge