name: CI/CD Debug PR Merged

on:
  pull_request:
    types:
      - closed
    branches: 
      - int-**
      - main


jobs: 

    print_event:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:

        - name: Checkout code
          uses: actions/checkout@v5

        - name: Print PR
          run: |
            echo  "/PR_${{ github.event.pull_request.number }} was merged."
           