name: CI/CD Automatic Process

on:
  push:
    branches: [ "feature/*"  ]
  # pull_request:
  #   branches: [ "int-*"  ]


jobs: 
  
    create_pull_request:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      outputs:
        pr_number: ${{ steps.create_pr.outputs.PR_NUMBER }}  

      environment:
        name: development
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Create Pull Request
          id: create_pr
          run: |
            gh pr create --head ${{ github.ref_name }} --base ${{ vars.DESTINATION_BRANCH }} --title "Pull request from ${{ github.ref_name }} to ${{ vars.DESTINATION_BRANCH }}"
