# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD Automatic Process

on:
  push:
    branches: [ "feature/*"  ]
  pull_request:
    branches: [ "feature/*"  ]


jobs:
    install_dependecies:
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
              python-version: "3.10"
              cache: 'pip'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt


    CreatePR:
      runs-on: ubuntu-latest
      outputs:
        pr_number: ${{ steps.create-pr.outputs.pr_number }}
      needs: install_dependecies
      environment:
        name: development
      steps:
        - uses: actions/checkout@v4            
        - name: Create PR
          id: create-pr
          run: | 
            echo pr_number=python ci_cd_scripts/github_create_pr.py --repo_slug ${{ github.repository }} --auth_token ${{ secrets.MY_GH_TOKEN }} --source ${{ github.ref }} --destination ${{ vars.DESTINATION_BRANCH }} >> $GITHUB_OUTPUT


        - name: Use Pull Request Number
          run: |
            echo "The pull request number is ${{ steps.create_pr.outputs.pr_number }}"

    trigger_tests:
    #name: unit_test
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      needs: install_dependecies

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v4
        - name: Run tests
          run: |
            python -m pip install pytest
            pytest