# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD Automatic Process

on:
  push:
    branches: [ "feature/*"  ]
  pull_request:
    branches: [ "feature/*"  ]


jobs:
    install_dependecies:
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
              python-version: "3.10"
              cache: 'pip'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    CreatePR:
      runs-on: ubuntu-latest
      environment:
        name: development
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
            
        - name: Create PR
          id: create-pr
          run: python ci_cd_scripts/github_create_pr.py --repo_slug ${{ github.repository }}
                                                  --auth_token ${{ secrets.MY_GH_TOKEN }}
                                                  --source ${{ github.ref }}
                                                  --destination ${{ vars.DESTINATION_BRANCH }}

        - name: Get Pull Request Number
          id: pr-number
          run: |
            echo "::set-output name=pr_number::$(python -c "print('$PR_NUMBER')")"
          env:
            PR_NUMBER: ${{ steps.create-pr.outputs.pull_request_number }}

        - name: Use Pull Request Number
          run: |
            echo "The pull request number is ${{ steps.pr-number.outputs.pr_number }}"

    trigger_tests:
    #name: unit_test
    # The type of runner that the job will run on
      runs-on: ubuntu-latest

      needs: install_dependecies

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v4
        - name: Run tests
          run: |
            python -m pip install pytest
            pytest